### ISSUE TITLE
Extract webvr demo to separate repository

### ISSUE THREAD

**Issue by JordanMajd** [blu-penguin/blu-penguin.github.io#12]
We should extract the New Belgium A-Frame demo to a separate repository and enable it as a project page. This will allow it be be accessed from our main website but keep the repositories separate.

For example if we had it in a repo called `newbelgium` and set up as a project page then we could access it at `bluepengu.in/newbelgium/`.

**Comment by adrian-chen** [comment]
What are the benefits of this?

**Comment by adrian-chen** [comment]
And how much time would it take?

**Comment by JordanMajd** [comment]
It would take less than 5 minutes.

This decouples and separates concerns of projects, allowing them to stand on their own.

The New Belgium demo and the website don't have anything in common and are essentially separate projects. Currently, they are coupled together in the same repository.

This adds complexity if we need to take an action on one project and not the other. Some example actions that come to mind: deploy, make repo private, password protect, run continuous  integration, customize build tooling, transfer IP etc... 

It is likely we will have many more A-Frame and other tech demos. Each one of these might have its own goals, objectives and client needs. While we may want to display these proejcts on our website, it is important to have concerns isolated because it allows us to be more flexible.
